### ISSUE TITLE
Lacking Documentation

### ISSUE THREAD

**Issue by rebeccaplowman** [activitree/meteor-push#31]
The only documentation is the code in the example directory in the repo. It requires opening several different tabs, correlating objects and functions between all those files, to figure out how to implement this package. This is the best option I've found for implementing push notifications in Meteor, but it is taking days for me to figure out what I need to include in a project just to get this package up and running.

**Comment by paulincai** [comment]
Things are pretty complex and requires to understand how Push works and how Firebase works.
The documentation includes everything you need to know, many people used this packages with just the documentation offered. There is not much more to say in the documentation because many things are Google and not Meteor.

The repo is not an application. In the Readme it is mentioned that the repo includes relevant folders with examples of files in the exact place where you should have them in your own project. You have examples of methods and a lot of defaults to start the deployment with.

You can always request paid support for your implementation.

**Comment by rebeccaplowman** [comment]
Documentation should include: What classes and methods are exported from activitree:push, how those methods correspond to the raw Google/Firebase methods, and what the methods do exactly. For example, the Push.send() method isn't just sending straight to the phonegap-push-plugin Push.send() method. There could be documentation of which parameters for each method are required or optional. I'd be willing to help write up that documentation, as I figure out this package. The fact that it is complex makes a good argument for investing in quality documentation, especially since this repo is the best Meteor package for push notifications that I've found.

**Comment by paulincai** [comment]
Ok, Push.send() method isn't just sending straight to the phonegap-push-plugin - the plugin is only involved in receiving a token and receiving notifications. Push doesn't sent anything to this plugin.
There are examples of methods as well as in the server side there is example of server configuration with all defaults and mandatory fields required by the package. I am not really sure why you feel these are missing. They may be missing from a PDF-like with bullet points but the repo actually features all the necessary information if you look in the examples and if you learn the Firebase side of things. I'd actually love to see some PRs on documentations, missing features etc.

**Comment by rebeccaplowman** [comment]
Yes, that is the issue. I have 5-7 tabs open in order to mentally correlate all the functions and how they are being used.
