### ISSUE TITLE
Paid Support Request

### ISSUE THREAD

**Issue by Ziyad33** [activitree/meteor-push#36]
I am struggling to implement this package in my project.
I came across [this issue](https://github.com/activitree/meteor-push/issues/31) and noticed that you offer paid support.

Where can I contact you for the paid support?

**Comment by paulincai** [comment]
Hi, due to a very busy schedule due to recent business developments, we are not ready to offer this at the moment. I hope I can answer some of your queries and help you walk through the documentation. Please note that this requires you to be familiar with the google libraries for which google offers extensive materials and examples.
